.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "42SHMAN" "" "November 2013" "" ""
.
.SH "NAME"
42sh \- The ROOTS SHell: a shell that don\'t segfault with only 2 bytes\.
.
.SH "SYNOPSIS"
\fB42sh\fR [options] [file]
.
.SH "COPYRIGHT"
.
.nf

42sh is licensed under the Beer\-Ware License by the hs24 team\.
.
.fi
.
.SH "DESCRIPTION"
\fB42sh\fR is probably the best SHell on the Internet\. \fB42sh\fR is an equivalent of \'bash \-posix\' meaning that it is intended to be a conformant implementation of the SHell and Utilies portion of the IEEE POSIX specification\.
.
.SH "OPTIONS"
\fB\-c\fR \fIstring\fR If the \-c option is present, then the commands are read from \fIstring\fR\.
.
.P
\fB[\-+]O\fR \fIshell option\fR Set or unset one of the shell options accepted by the shopt \fIbuiltin\fR\.
.
.P
\fB\-\-norc\fR Ignore the resources files \fI~/\.42shrc\fR and \fI/etc/42shrc\fR
.
.P
\fB\-\-ast\-print\fR Display the Abstract Syntax Tree of all the commands\.
.
.P
\fB\-\-version\fR Display the version on standard output and exit\.
.
.P
\fB\-\-help\fR Display a usage message on standard output and exit\.
.
.SH "BUILTINS"
\fITODO\fR
.
.SH "AUTHOR"
Rémi `halfr` Audebert
.
.P
Nassim `Nass` Eddequiouaq
.
.P
Paul `Dettorer` Hervot
.
.P
Antoine `Serialk` Pietri
.
.P
Adrien `schischi` Schildknecht
.
.SH "SEE ALSO"
\fBbash\fR(1) \fBbeer\fR(7) \fBsh\fR(1)
.
.SH "BUG REPORTS"
If you find a bug in 42sh, you should report it\. But please make sure to run the latest version of 42sh available at \fIhttp://42sh\.greenit\-over\-the\-cloud\.fr\fR
.
.P
To report a bug, just send a letter or sms to \fIDave Null\fR, with the following things:
.
.IP "\(bu" 4
The version number
.
.IP "\(bu" 4
If you are using FreeBSD or not
.
.IP "\(bu" 4
A description of the bug and how to reproduce it
.
.IP "\(bu" 4
A tasteful beer
.
.IP "" 0

